#!/usr/bin/env ruby

# DOC RUBY : https://ruby-doc.org/3.3.5/

# irb pour lancer interpreteur interactif

# Mettre chmod +x monfichier.rb

# Type Primaire :

#1. Les Entiers
6 + 4
2 ** 4 #** pour faire puissance

#2. Les Chaines de 'Caractères' ""
#sting 

#3. Les Booléens Exemple true ou false

puts = "character"

# Exemple de conversion en minuscules
texte = "BONJOUR , TOUT LE MONDE"
texte_en_minuscule = texte.downcase

puts texte_en_minuscule  # Résultat : "bonjour tout le monde"

#Chaîne multi-ligne : Utilisez des guillemets triples (<<~TEXT) 
message = <<~TEXT
Première ligne
Deuxième ligne
Troisième ligne
TEXT

puts message

# ASCII puts
puts 97.chr
puts 122.chr

#Les Boucles ( Attention WHILE , Rajouter true)
i= 0
while i < 10
  i = i + 1
  puts i
end

# While Avec True 
i= 0
while true
  i = i + 1
  puts i
end
